FROM cypress/included:14.0.1


WORKDIR /e2e


RUN npm install -g pnpm

COPY ./cypress /e2e/cypress
COPY ./package.json /e2e/package.json
COPY ./pnpm-lock.yaml /e2e/pnpm-lock.yaml
COPY ./cypress.config.ts /e2e/cypress.config.ts


RUN pnpm install


CMD ["pnpx", "cypress", "run"]
