# Use official Node.js image as a base image
FROM node:21-alpine

# Set working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy the package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application files
COPY . .

# Expose the port your Next.js app runs on
EXPOSE 3000

# Run the Next.js application
CMD ["pnpm", "dev"]
